### ISSUE TITLE
Bump rxdart version

### ISSUE THREAD

**Issue by ccavolt** [braverhealth/phoenix-socket-dart#94]
Is there a reason why rxdart version is semi-pinned? If not, can it be upgraded to 0.28.0? It's preventing me from using a newer version of custom_lint.

**Comment by matehat** [comment]
Would that work? https://github.com/braverhealth/phoenix-socket-dart/pull/95

**Comment by ccavolt** [comment]
Yes, it should. Thank you very much!

**Comment by ccavolt** [comment]
Saw you merged the pr; do you mind doing a point release?

**Comment by matehat** [comment]
Done!

**Comment by ccavolt** [comment]
I'm writing this for posterity...I made a mistake with this issue, stemming from a misunderstanding of pre-1.0.0 Semantic Versioning. ^0.27.0 is not the same as ">=0.27.0 <1.0.0", so the version range that was there previously may be more appropriate, as ^0.27.0 doesn't fix my issue of compatibility with rxdart version 0.28.0, so I had to do a dependency override anyway.
